### ISSUE TITLE
Delete all messages and old messages loading

### ISSUE THREAD

**Issue by Vndtta** [surespot/android#104]
Hi, since the last two weeks 3 people around me (including me) are having the same issue. Suddenly surespot loads old messages in the conversation so you are not able to read the current conversation, furthermore everything you write after the message load is written _above_ those messages so you can't really follow anything.

What I did is delete all messages, but to my surprise, deleting all messages don't delete them from the server, neither from the other person whom I'm talking to. I think if you should be able to delete all your messages from the server and the other person if you want, and not going one by one.

Thanks

**Comment by 2fours** [comment]
Cassandra has been updated to v2.1.15 which should fix this issue.
