### ISSUE TITLE
FFMPEG Binary issue in lollipop

### ISSUE THREAD

**Issue by Thiru2Moorthy** [surespot/android#114]
Hi 

I tried to use your FFMPEG library in one of my Android app which is expected to work in 5.x (Lollipop).

When I issued a command to trim/compress a video, the following message is thrown in logcat. 

"/storage/emulated/0/DCIM/Camera/VID_20150127_123957.mp4: Invalid data found when processing input". 

The video was shot the camera itself and gets trimmed fine with a FFMPEG binary created for Windows x64.

I am not sure whether this is the right place to post for help. If not, please be kind enough to suggest an alternate forum.

Thanks.

**Comment by 2fours** [comment]
Our ffmpeg binary is compiled to only convert the audio file format we are using in surespot hence the error. You can use https://github.com/guardianproject/android-ffmpeg to compile your own.
