### ISSUE TITLE
push will no longer work!?

### ISSUE THREAD

**Issue by zoff99** [surespot/android#118]
C2DM deprecation Beginning this April, Android Cloud to Device Messaging (C2DM) will be fully deprecated and no longer supported. C2DM is being replaced by Google Cloud Messaging (GCM), the next generation of C2DM. Please note that C2DM push messaging will no longer function properly if your app does not migrate to the latest GCM library.

If you have any apps that still use C2DM, we strongly urge you migrate to GCM as soon as possible. You can see if you’re using C2DM by checking if you’re using a gcm.jar library or GCM helper libraries (http://goo.gl/DuYt9w) in your implementation. If none of your apps use C2DM, there is no action required on your part. 

Learn more (http://goo.gl/cYj0Ks).

**Comment by zoff99** [comment]
is the project dead? hello?

**Comment by 2fours** [comment]
We already use GCM.
