### ISSUE TITLE
"surespot could not create http clients.. is storage space available? Shutting down"

### ISSUE THREAD

**Issue by v6** [surespot/android#123]
I received this message when I entered my password after I lost access to my credential storage. 

There is at least 100mb of available space on the device. 

I'm not sure why I am seeing an error like this. 

https://github.com/surespot/android/blob/master/res/values/strings.xml

**Comment by tuyen-tran** [comment]
I am also receiving this error.  This is from a previously working install and authenticated.

**Comment by v6** [comment]
// , This was used on a T-Mobile ZTE phone.

**Comment by 2fours** [comment]
Does logging out and "clear local cache" from the login screen help? Can also try clearing data for surespot in android settings. (Make sure you backup your identity first).

**Comment by v6** [comment]
Tried both of these. No luck.

**Comment by 2fours** [comment]
What about uninstalling and reinstalling (backup identity first). Are you installing to the sdcard or anything like that?

**Comment by v6** [comment]
// , Someone stole the phone in question before I could reinstall it, and
I was hesitant to reinstall it because I could not (obviously) log in to
make a back-up.

**Comment by 2fours** [comment]
If the phone's rooted you could copy the identity folder somewhere, uninstall, reinstall, then copy it back.

**Comment by v6** [comment]
// , Someone stole the phone in question before I could reinstall it.

**Comment by 2fours** [comment]
Using OKHTTP now and the code that generates the above error has been removed.

**Comment by v6** [comment]
// , Can I assume that I'll still lose access to my identity if my credential storage is removed or deleted, even if I enter a correct pass phrase?
