### ISSUE TITLE
build path contains duplicate entery: 'src' for project 'surespot'

### ISSUE THREAD

**Issue by alhaddadsoft** [surespot/android#125]
![default](https://cloud.githubusercontent.com/assets/12938778/8211880/7b336844-1521-11e5-9b5e-19be9bb0b4f4.png)
![Uploading بدون عنوان.png…]()

i always get this error when i try to import the android source to eclipse , 
build path contains duplicate entery: 'src' for project 'surespot'

the files gets imported in the workspace but when res\layout it shows an error in the second layout when i delete it it keeps giving an error in th next layout .

how can i solve this i am new to java and android developing .

**Comment by jack71** [comment]
i appreciate that

**Comment by roy128** [comment]
:+1:

**Comment by 2fours** [comment]
Master is using android studio now.
