### ISSUE TITLE
Unable to build the project in Android Studio

### ISSUE THREAD

**Issue by flyeminent** [surespot/android#126]
Hi fellows,
I am trying to build the project using Android Studio (AS). I am using "androidstudio" branch.
I first imported the whole folder to a AS project. Then I synced the project with Gradle. Then I got some conflict attributes (see screenshot below). Does anybody know who to resolve it?
![as](https://cloud.githubusercontent.com/assets/13148474/8494972/4c6a725a-219c-11e5-8c96-76e31471a24e.png)

**Comment by 2fours** [comment]
Should be fixed in master now.
