### ISSUE TITLE
All messages gone and stuck on "loading and decrypting..." after using back button to go to homescreen and opening the app again.

### ISSUE THREAD

**Issue by txtsd** [surespot/android#128]
Happens every time I do it.
Android 5.1.1
Nexus 6

**Comment by 2fours** [comment]
Can you logout and "clear local cache" from the login screen and see if that helps.

**Comment by txtsd** [comment]
It kept getting stuck at "logging in", but it managed to log in after a force close.
Now I can only see the messages I've sent. Everything from the other person has been lost.

**Comment by 2fours** [comment]
Is it possible the other person deleted their messages?

**Comment by txtsd** [comment]
Uh, they actually did and didn't tell me until I asked -_-
