### ISSUE TITLE
Unable to execute dex: Method ID not in [0, 0xffff]: 65536

### ISSUE THREAD

**Issue by rahulbbbose** [surespot/android#129]
I am trying to run surespot android on my macbook and I keep running into the below error 

    [2015-09-17 20:38:06 - Dex Loader] Unable to execute dex: method ID not in [0, 0xffff]: 65536
    [2015-09-17 20:38:06 - Zephyr] Conversion to Dalvik format failed: Unable to execute dex: method ID not in [0, 0xffff]: 65536`

I tried all the solutions I can find on Stackoverflow. 

Below is the screenshot.

![screen shot 2015-09-17 at 8 38 34 pm](https://cloud.githubusercontent.com/assets/14331804/9949807/49bfe394-5d80-11e5-8ec7-13d93a806fde.png)

I renamed the application to Zephyr. I hope that is not the issue.
Kindly let me know if anybody else is having this issue or if there is a solution to this.

Below is my environment:
- osx Yosmite (10.10.5)
- Eclipse 4.4.0
- I tried with genymotion and with an actual android device and none seem to be working

Thanks in advance.

**Comment by 2fours** [comment]
Should be fixed in master now.

**Comment by rahulbbbose** [comment]
Thanks a lot for the quick response. You guys are amazing.

I am unable to test it because the project now throws an error in the file *activity_billing.xml* in surespot project. The error is in the below piece of code

    <Button style="@style/Widget.Sherlock.ActionButton"

And the errors reads as below

>error: Error: No resource found that matches the given name (at 'style' with value '@style/
 Widget.Sherlock.ActionButton').

**Comment by 2fours** [comment]
You should be using android studio not eclipse.
