### ISSUE TITLE
Reviews of Insecurity

### ISSUE THREAD

**Issue by Sepero** [surespot/android#132]
There are negative reviews floating around the internet (on websites and play store), about Surespot being compromised or revealed to Government officials. Please put up a simple page on the website to let everyone know that Surespot has not given server information (metadata) to Government Officials. Best Regards.

**Comment by 2fours** [comment]
We have published 2 blog posts about this: http://surespotencryptedmessenger.blogspot.com/

**Comment by Sepero** [comment]
That is excellent! If it is not too much to ask, I'd like to also request a "Canary page", so that users can remain confident now and into the future. Thank you very much.

https://en.wikipedia.org/wiki/Warrant_canary
