### ISSUE TITLE
R.raw.configuration not found

### ISSUE THREAD

**Issue by satishkadyan** [surespot/android#139]
InputStream rawResource = context.getResources().openRawResource(R.raw.configuration);

raw is not found in surespot common library within SurespotConfiguration.java

cloned master current, it not able to build project.
please suggest if going to update project soon, or should switch to other release versions.

**Comment by zoff99** [comment]
adam has never included this file. maybe on purpose?

create it like this

mkdir -p ./surespotcommon/src/main/res/raw ;
printf 'ssl_strict=true\nbaseUrl=https://server.surespot.me:443\n' > ./surespotcommon/src/main/res/raw/configuration.properties ;

or use my repo to build it on circleCI:
https://github.com/zoff99/surespot-android/blob/v66_simple/circle.yml

but the latest v0.66 will build but not work correctly!
maybe some code is still missing ...

**Comment by zoff99** [comment]
https://circleci.com/gh/zoff99/surespot-android/402#artifacts

**Comment by satishkadyan** [comment]
ok thanks, 

i will try as directed above :)

**Comment by Dubz** [comment]
This literally drove me nuts for hours because I'm still new to Android development. Finally started Googling around for answers and stumbled across this by searching for the file in the repo and finding the issue. No idea why it's not in the repo, it's necessary to run the app...
