### ISSUE TITLE
Remove option for private key backup to the NSA

### ISSUE THREAD

**Issue by Le1b1** [surespot/android#35]
This is a serious security issue, most users passwords will be brutforceable with ease. 
Provide a way of restoring the identity with exposing the private key (e.g. like Threema).

**Comment by akerbos** [comment]
If I used an iOS device I would not worry about some cloud service siphoning my data. Seriously, if you care about privacy you need another phone.

**Comment by 2fours** [comment]
On iOS you can backup the identity on the phone to "Documents" then connect the phone to iTunes and download the identity (.ssi) file via File Sharing in iTunes.
