### ISSUE TITLE
standardize emoticon icon next to text input

### ISSUE THREAD

**Issue by grrrrr** [surespot/android#48]
It would be good to stick to one icon for the emoticon on the left of the text entry field in chat window.  The current option to display a random emoticon next to the input field is quite distracting and unintuitive.

**Comment by wp9015362** [comment]
+1

By the way, seems to be the same request as:

https://github.com/surespot/android/issues/103

**Comment by 2fours** [comment]
Version 70 does not change the icon.

**Comment by grrrrr** [comment]
@2fours if the new version does not make the suggested change why close the ticket?  At least mark it `won't fix` or something if you have no plan to address it.

**Comment by 2fours** [comment]
It's "fixed". Version 70 does not randomize the icon any more.
