### ISSUE TITLE
Feature request: BACK button in any conversation returns to Contacts instead of minimize app

### ISSUE THREAD

**Issue by snappycow** [surespot/android#85]
As the title says, currently when in any conversation thread, pressing BACK will minimize the app. 

Common behavior in other apps when pressing BACK in a conversation would return back to the main list of contacts. I think surespot would be more useable if this was the default behavior as well.

I think this should be quite do-able, perhaps as a user selectable option. But no urgency, would much rather all efforts be directed at implementing the group chat feature :)

**Comment by 2fours** [comment]
This is achieved by version 70.
