### ISSUE TITLE
deleted messages still present

### ISSUE THREAD

**Issue by grrrrr** [surespot/android#87]
Surespot: v58
Android: Cyanogen Mod 10.2.1-jfltexx

**Issue**
It appears that the delete message function does not work correctly and that _deleted_ messages are only hidden from view.

**What happens**
1. Delete a full message thread with _person1_
2. start a new conversation with _person1_
3. Quit surespot or let it auto log out or reboot phone
4. Open conversation thread. 
5. you will briefly be presented with the conversation thread deleted at _step 1_ before thread refreshes and you are shown conversation thread from _step 2_ and the first thread is removed/hidden again

**What should happen**
1. Delete a full message thread with _person1_
2. start a new conversation with _person1_
3. Quit surespot or let it auto log out or reboot phone
4. Open conversation thread.
5. you only see the last _undeleted_ thread as the first was _actually_ deleted.

**Comment by 2fours** [comment]
There was a bug in cassandra that caused this sometimes. Cassandra has since been updated.
